In [9]:
#Dependencies
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from statistics import mean, median, mode

In [10]:
#load csv files
city_df = pd.read_csv("generated_data/city_data.csv")
ride_df = pd.read_csv("generated_data/ride_data.csv")

In [11]:
#Group ride csv file by 'city' column
ride_group = ride_df.groupby('city')

#Calculate average fare per city  
avg_fare_df = ride_group['fare'].mean()

#Calculate total riders per city
total_riders_df = ride_group['ride_id'].count()

In [13]:
# Merge datasets on "city" so that no data is lost (should be 182 rows)
combined_data_df = pd.merge(avg_fare_df, total_riders_df, how='outer', on='city')
combined_data_df

ValueError: can not merge DataFrame with instance of type <class 'pandas.core.series.Series'>

In [5]:
# Merge datasets on "city" so that no data is lost (should be 182 rows)
combined_data_df = pd.merge(city_df, ride_df, how='outer', on='city')
combined_data_df

,city,driver_count,type,date,fare,ride_id
0,Tammyburgh,11,Urban,2017-01-02 10:56:28,12.40,7963408790849
1,Tammyburgh,11,Urban,2017-01-02 04:28:03,18.78,2315208159060
2,Tammyburgh,11,Urban,2017-01-03 03:00:08,30.10,558639764959
3,Tammyburgh,11,Urban,2017-01-01 00:10:21,7.76,9113511454178
4,Tammyburgh,11,Urban,2017-01-02 05:22:44,22.00,4171010688543
5,Tammyburgh,11,Urban,2017-01-02 21:29:38,5.37,5531485446571
6,Tammyburgh,11,Urban,2017-01-02 23:58:17,11.68,1012442651497
7,Tammyburgh,11,Urban,2017-01-02 21:10:16,31.16,7261786411548
8,Tammyburgh,11,Urban,2017-01-02 00:43:50,10.64,9221421228793
9,Tammyburgh,11,Urban,2017-01-01 12:39:10,9.88,6250336876297
10,Tammyburgh,11,Urban,2017-01-01 14:13:26,23.97,851102797493
11,Tammyburgh,11,Urban,2017-01-01 07:25:05,32.90,3093940598123
12,Tammyburgh,11,Urban,2017-01-01 11:13:16,5.94,6301143210542
13,Tammyburgh,11,Urban,2017-01-01 13:44:35,10.27,1995784061110
14,Tammyburgh,11,Urban,2017-01-02 13:20:45,41.04,4635225467442
15,Tammyburgh,11,Urban,2017-01-01 06:49:00,27.48,5635061147330
16,Tammyburgh,11,Urban,2017-01-02 23:28:35,22.43,4240585503749
17,Tammyburgh,11,Urban,2017-01-01 11:50:03,8.40,7691252503666
18,Tammyburgh,11,Urban,2017-01-01 17:51:31,21.39,3874929768672
19,Tammyburgh,11,Urban,2017-01-01 05:28:50,37.84,8096350011706
20,Tammyburgh,11,Urban,2017-01-01 19:56:38,43.11,1746878188615
21,Tammyburgh,11,Urban,2017-01-01 06:44:03,21.27,5035612751038
22,Melissaborough,15,Urban,2017-01-01 08:55:58,19.59,2791839504576
23,Melissaborough,15,Urban,2017-01-02 18:40:34,17.73,6817245215298
24,Melissaborough,15,Urban,2017-01-02 04:37:01,20.88,3220484578919
25,Melissaborough,15,Urban,2017-01-01 00:09:46,26.12,7153857415916
26,Melissaborough,15,Urban,2017-01-01 23:07:17,25.79,1488790166684
27,Melissaborough,15,Urban,2017-01-01 23:11:26,34.98,6892029262149
28,Melissaborough,15,Urban,2017-01-02 13:23:57,7.49,9465996268581
29,Melissaborough,15,Urban,2017-01-01 14:50:53,16.79,208766967340
...,...,...,...,...,...,...
2345,South Jacobside,7,Rural,2017-01-02 03:47:17,16.68,6460890149427
2346,South Jacobside,7,Rural,2017-01-01 09:59:41,50.25,9699456082855
2347,Sheltonhaven,1,Rural,2017-01-02 19:36:24,23.37,79816330366
2348,Sheltonhaven,1,Rural,2017-01-01 15:07:56,20.83,7026755023852
2349,Sheltonhaven,1,Rural,2017-01-02 13:58:15,29.05,5214265726789
2350,Sheltonhaven,1,Rural,2017-01-02 08:32:57,18.85,9738620586963
2351,Sheltonhaven,1,Rural,2017-01-02 22:34:53,21.25,6231484957991
2352,Port Darrellhaven,10,Rural,2017-01-01 06:20:30,24.00,792456027334
2353,Port Darrellhaven,10,Rural,2017-01-03 12:13:45,59.94,774396990381
2354,Port Darrellhaven,10,Rural,2017-01-01 05:46:48,45.68,6638823058393
2355,Port Darrellhaven,10,Rural,2017-01-03 03:05:40,23.54,3948790730509
2356,Port Darrellhaven,10,Rural,2017-01-01 11:34:12,52.88,1444325423615
2357,Port Darrellhaven,10,Rural,2017-01-03 07:23:10,14.61,4374249469802
2358,Port Darrellhaven,10,Rural,2017-01-01 04:10:10,30.40,392383576464
2359,Hoganfort,5,Rural,2017-01-02 20:16:34,40.93,6483221995142
2360,Hoganfort,5,Rural,2017-01-02 18:47:37,43.55,4196138442037
2361,Hoganfort,5,Rural,2017-01-02 18:35:37,44.82,167986984288
2362,Hoganfort,5,Rural,2017-01-01 21:25:09,18.67,3640401335874
2363,Hoganfort,5,Rural,2017-01-03 09:23:12,54.73,1963628462690
2364,Hoganfort,5,Rural,2017-01-02 12:58:49,12.30,1724026188236
2365,Hoganfort,5,Rural,2017-01-03 09:41:46,37.83,2074313960632
2366,Hoganfort,5,Rural,2017-01-02 12:11:54,21.91,9413449360993
2367,Hoganfort,5,Rural,2017-01-02 20:30:22,22.28,6317412291785
2368,Hoganfort,5,Rural,2017-01-03 12:15:48,19.35,685572928589
2369,Hoganfort,5,Rural,2017-01-01 04:12:33,24.47,8232643860877
2370,South Brittany,9,Rural,2017-01-01 17:03:55,50.76,7485767610649
2371,South Brittany,9,Rural,2017-01-02 08:34:13,31.40,8735856224615
2372,South Brittany,9,Rural,2017-01-02 23:08:44,11.56,1094056539538
2373,South Brittany,9,Rural,2017-01-02 18:04:04,16.11,2930708191671
2374,South Brittany,9,Rural,2017-01-03 12:15:51,47.94,9037804247547

In [8]:
# Create a new dataframe: average fare and total rides per city
AvgFare_TotalRides = combined_data_df.loc[(combined_data_df["fare"].mean()) & (combined_data_df["ride_id"].count())]

# Set the index of this new dataframe by city
AvgFare_TotalRides = AvgFare_TotalRides.set_index("city")

AvgFare_TotalRides.head()

TypeError: ufunc 'bitwise_and' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''